[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["src", "tests"]
multi_line_output = 3

[tool.ruff]
target-version = "py39"
line-length = 100

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "N",   # pep8-naming
  "UP",  # pyupgrade
  "S",   # bandit
  "B",   # flake8-bugbear
  "C4",  # comprehensions
  "SIM", # flake8-simplify
  "PERF",
  "RUF"
]
ignore = [
  "E203",  # whitespace before ':' (black compatibility)
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["S101", "S105", "S106"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
strict_optional = true
exclude = ["tests/"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 70


